ALTER TABLE professional
ADD COLUMN IF NOT EXISTS gender VARCHAR(20) CHECK (gender IN ('MULHER', 'HOMEM', 'PESSOA_NAO_BINARIA', 'PREFIRO_NAO_INFORMAR', 'OUTRO'));

ALTER TABLE professional
ADD COLUMN IF NOT EXISTS  consent_gender_sharing BOOLEAN;
